### ISSUE TITLE
download-release.shtml 404

### ISSUE THREAD

**Issue by dcoobs** [aquamacs-emacs/aquamacs-web-site#20]
I'm getting a 404 error when I try to access https://aquamacs.org/download-release.shtml.

**Comment by treese** [comment]
Thanks for the report. Did you get that link from the current web site, or does it appear somewhere else?

When we reconstructed the web site, we changed that particular link, but we can see about fixing it in some way if it's linked from elsewhere for good reasons.

**Comment by dcoobs** [comment]
The [AutoPkg community was using it](https://github.com/autopkg/hansen-m-recipes/blob/master/Aquamacs/Aquamacs.download.recipe) for automated downloads to import into endpoint management systems. Is there a new URL we should be using now? If so, I can make a pull request to update things on our end.

**Comment by treese** [comment]
Working on trying to figure out what the best solution to this is. Thanks for pointing it out.

**Comment by azerella** [comment]
@dcoobs What's the specific file you're looking for from that link? Perhaps it could be fetched from the GitHub releases page or our nightly download?

I've added back `download-release.shtml` which redirects to https://github.com/davidswelt/aquamacs-emacs/releases/download/Aquamacs-3.5/Aquamacs-Emacs-3.5.dmg as an interim solution, was this the file you were after?

**Comment by treese** [comment]
@dcoobs If Adam's fix does what you expect, I think the problem has been solved. It makes sense for us to continue having a stable link for "fetch the latest release kit", and this would do it.

Sorry for the inconvenience!

**Comment by rustymyers** [comment]
Hello, I maintain the download recipe of Aquamacs for AutoPkg. Thanks for adding the download-release.shtml back, this is helpful for our recipes. We are now able to download the latest version again with this URL. Thank you, Rusty

**Comment by treese** [comment]
Hi, Rusty. Glad it works now. And thanks for helping get Aquamacs out to more people!
